allup/Models/Slider.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ALLUP2.Models
{
    public class Slider
    {
        public int Id { get; set; }
        [Required]
        [StringLength(maximumLength: 100)]
        public string Title1 { get; set; }
        [Required]
        [StringLength(maximumLength: 100)]
        public string Title2 { get; set; }
        [Required]
        [StringLength(maximumLength: 800)]
        public string Description { get; set; }
        public string RedirectUrl { get; set; }
        public string? Image { get; set; }
        [NotMapped]
        public IFormFile? ImageFile { get; set; }
        

    }
}

allup/Areas/Admin/Controllers/SliderController.cs
using ALLUP2.DAL;
using ALLUP2.Models;
using Microsoft.AspNetCore.Mvc;

namespace ALLUP2.Areas.admin.Controllers
{
    [Area ("Admin")]
    public class SliderController : Controller
    {
        private readonly AppDbContext _context;
        public SliderController(AppDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            List<Slider> Sliders = _context.Sliders.ToList();
            return View(Sliders);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Slider slider)
        {
            if(!ModelState.IsValid) return View(slider);
            slider.Image = slider.ImageFile.FileName;
            _context.Sliders.Add(slider);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }


    }
}

allup/Areas/Admin/Views/Slider/Create.cshtml
@model Slider
<h1>Crate Service</h1>
<form method="post" enctype="multipart/form-data">
    <div class="mb-3">
        <label for="" class="form-label">Title1</label>
        <input asp-for="Title1" type="text" class="form-control">
        <span asp-validation-for="Title1" style="color:red"></span>
    </div>
    <div class="mb-3">
        <label for="" class="form-label">Title2</label>
        <input asp-for="Title2" type="text" class="form-control">
        <span asp-validation-for="Title2" style="color:red"></span>
    </div>
    <div class="mb-3">
        <label for="" class="form-label">Description</label>
        <input asp-for="Description" type="text" class="form-control">
        <span asp-validation-for="Description" style="color:red"></span>
    </div>

    <div class="mb-3">
        <label for="" class="form-label">Redirect-Url</label>
        <input asp-for="RedirectUrl" type="text" class="form-control">
        <span asp-validation-for="RedirectUrl" style="color:red"></span>
    </div>

    <div class="mb-3">
        <label for="" class="form-label">Image</label>
        <input asp-for="ImageFile" type="file" class="form-control">

    </div>

    <button type="submit" class="btn btn-primary w-25">Submit</button>
</form>

allup/Areas/Admin/Views/Slider/Index.cshtml
@model List<Slider>
<div class="container-fluid">
    <a asp-action="Create" asp-controller="Slider" class="btn btn-primary">Create</a>
    <table class="table table-striped shadow mt-4">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Title1</th>
                <th scope="col">Title2</th>
                <th scope="col">Desc</th>
                <th scope="col">Image</th>
                <th scope="col">Actions</th>

            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <th scope="row">1</th>
                    <td>@item.Title1</td>
                    <td>@item.Title2</td>
                    <td>@item.Description</td>
                    <td><img src="~/assets/images/@item.Image" style="width=30%; height=30%"/></td>

                    <td>
                        <a asp-action="Update" asp-controller="Slider" asp-route-id="@item.Id" class="btn btn-primary">Update</a>
                        <a asp-action="Delete" asp-controller="Slider" asp-route-id="@item.Id" class="btn btn-secondary">Delete</a>

                    </td>
                </tr>
            }

        </tbody>
    </table>

</div>