allup/Models/Tag.cs
namespace ALLUP2.Models
{
    public class Tag
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public List<ProductTag>? ProductTags { get; set; }
    }
}

allup/Areas/Admin/Controllers/TagController.cs
using ALLUP2.DAL;
using ALLUP2.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace ALLUP2.Areas.Admin.Controllers
{
    [Area("admin")]
    public class TagController : Controller
    {
        private readonly AppDbContext _context;

        public TagController(AppDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            List<Tag> tags = _context.Tags.ToList();
            return View(tags);
        }
        public IActionResult Create()
        {

           
            return View();
        }
        [HttpPost]
        public IActionResult Create(Tag tag)
        {

            if (_context.Tags.Any(t => t.Name.ToLower() == tag.Name.ToLower()))
            {
                ModelState.AddModelError("Name", "Tag has created");
                return View();
            }

            if (!ModelState.IsValid)
            {

                return View();
            }

   

            _context.Tags.Add(tag);
            _context.SaveChanges();

            return RedirectToAction("index");
        }
        public IActionResult Update(int id)
        {

            if (id == null) return NotFound();

            Tag tag = _context.Tags.FirstOrDefault(t => t.Id == id);

            if (tag == null) return NotFound();

            return View(tag);

        }
        [HttpPost]
        public IActionResult Update(Tag tag)
        {

         

            if (!ModelState.IsValid)
            {
                return View();
            }
            Tag existTag = _context.Tags.FirstOrDefault(t => t.Id == tag.Id);
            if (existTag == null) return NotFound();

            if (_context.Tags.Any(t => t.Id != tag.Id && t.Name.ToLower() == tag.Name.ToLower()))
            {
                ModelState.AddModelError("Name", "Tag has  created!");
                return View();
            }
            existTag.Name = tag.Name;

            _context.SaveChanges();
            return RedirectToAction("Index");
        }
        public IActionResult Delete(int id)
        {
            if (id == null) return NotFound();

            Tag tag = _context.Tags.FirstOrDefault(t => t.Id == id);
            return View(tag);
        }

        [HttpPost]
        public IActionResult Delete(Tag tag)
        {

            Tag existTag = _context.Tags.FirstOrDefault(t => t.Id == tag.Id);

            if (existTag == null)
            {
                return NotFound();
            }

            _context.Tags.Remove(existTag);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }


    }
}

allup/Areas/Admin/Views/Tag/Create.cshtml
@model Tag
<div class="container-fluid">
    <h1>Create Tag:</h1>
    <div class="row justify-content-center flex-column align-items-center">
        <form class="col-md-8" method="post">
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label asp-for="Name">Name</label>
                    <input asp-for="Name" class="form-control" placeholder="Name">
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
            </div>
            

            <button type="submit" class="btn btn-primary">Create</button>
            <a class="btn btn-primary" asp-action="Index" asp-controller="Tag">Back</a>
        </form>
    </div>
</div>

allup/Areas/Admin/Views/Tag/Delete.cshtml
@model Tag
<form method="post">
    <div class="container-fluid">
        <div class="card">
            <div class="card-header">
                <h2 >Delete Tag: </h2>
            </div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item">@Model.Name</li>
            </ul>
        </div>
        <a class="btn btn-success" asp-action="Index" asp-controller="Tag">Back</a>
        <button type="submit" class="btn btn-danger">Delete</button>
    </div>
</form>

allup/Areas/Admin/Views/Tag/Index.cshtml
@model List<Tag>;
@{
    int counter = 0;

}
<div class="container-fluid">
    <div class="d-flex align-items-center justify-content-between">
        <h1>Tags :</h1>
        <a class="btn btn-primary" style="width:100px;" asp-action="Create" asp-controller="Tag">Create</a>
    </div>

    <table class="table table-hover table-striped mt-3 shadow">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Name</th>
                <th scope="col">Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var product in Model)
            {
                counter++;
                <tr>
                    <th scope="row">@counter</th>
                    <td>@product.Name</td>
                    <td>
                        <a class="btn btn-warning" asp-action="Update" asp-controller="Ta" asp-route-id="@product.Id">Update</a>
                        <a class="btn btn-danger" asp-action="Delete" asp-controller="Tag" asp-route-id="@product.Id">Delete</a>
                    </td>
                </tr>

            }
        </tbody>
    </table>
</div>

allup/Areas/Admin/Views/Tag/Update.cshtml
@model Tag
<div class="container-fluid">
    <h1>Update Tag:</h1>
    <div class="row justify-content-center flex-column align-items-center">
        <form class="col-md-8" asp-action="Create" method="post">
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label asp-for="Name">Name</label>
                    <input asp-for="Name" class="form-control" placeholder="Name">
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
            </div>
            <button type="submit" class="btn btn-primary">Update</button>
            <a class="btn btn-primary" asp-action="Index" asp-controller="Tag">Back</a>
        </form>
    </div>
</div>